language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install libtag1-dev libunittest++-dev

install:
  - cmake CMakeLists.txt
  - make

script: ./build/libfb2k/fb2ktest

branches:
  only:
    - master
