language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update -q
  - sudo apt-get install -y libtag1-dev
  - sudo apt-get install -y libunittest++-dev

install:
  - cmake CMakeLists.txt
  - make

script:
  - cd build/libfb2k
  - ./fb2kTest

branches:
  only:
    - master
