language: cpp

compiler:
  - gcc
  - clang

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libtag1-dev/precise-backports
- sudo apt-get install -y libunittest++-dev

install:
  - cmake CMakeLists.txt
  - make

script: ./build/libfb2k/fb2ktest

branches:
  only:
    - master
